- name: Play level variables ..
  hosts: localhost
  connection: local
  vars:
    course: "Ansible for beginners"
    duration: "2 days"
    trainer: "Shiva Kumar"
  tasks:
  - name: Display course details
    ansible.builtin.debug:
      msg: "Course: {{ course }}, Duration: {{ duration }}, Trainer: {{ trainer }}"

    