- name: variables from a file
  hosts: local
  connection: local
  tasks:
  - name: Display course details
    vars:
      trainer: "Shiva K"
    ansible.builtin.debug:
      msg: "Course: {{ COURSE }}, Duration: {{ DURATION }}, Trainer: {{ TRAINER }}"