- name: check the facts
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install nginx if RHEL
    ansible.builtin.dnf:
      name: nginx
      state: latest
    when: ansible_os_family== "RedHat" #if we want to use anything from ansible facts we should keep "ansible_*" . example: "pkg_mgr": "dnf" --> ansible_pkg_mgr

  - name: install nginx if DEBIAN
    ansible.builtin.apt:
      name: nginx
      state: latest
    when: ansible_os_family== "Debian"

#ansible will write this for us by default in the background (in some situatuins where ansible can't do this , we can explicitly extract the data and mention as above)-> heterogeneous -> this is the drawbag in the shell that ansible is solving